language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
 - pip install -r requirements.txt
 - pip install codacy-coverage

# command to run tests
script:
 - pytest pytest --cov=app  --cov-report=xml

after_success:
  - python-codacy-coverage -r coverage.xml